### ISSUE TITLE
[BUG] Wrong Video Align

### ISSUE THREAD

**Issue by BlackYuzia** [tamius-han/ultrawidify#125] opened 2020-12-13 15:02 UTC
**Describe the bug**
When I first time open any video on youtube I get left align video. But in settings I setup "center".
When I open (in full screen) video and then exit from full screen video 

**To Reproduce**
1. Open new video (video what once opened per session didn't have this bug/trouble/issue).
2. Saw what your video moved to left corner.
3. Profit?

**Expected behavior**
Normal: Video position should be on middle / center. 
Best: Video should by load open in full size (maybe I should change mode from hybrid to basic or etc?)

**Screenshots**

Wrong pos:
![image](https://user-images.githubusercontent.com/25010528/102015180-a8063300-3d62-11eb-9e18-06870a060c27.png)
![image](https://user-images.githubusercontent.com/25010528/102015225-ebf93800-3d62-11eb-8e66-638b3cebf51e.png)
Align before fullscreen:
![image](https://user-images.githubusercontent.com/25010528/102015471-8312bf80-3d64-11eb-8b25-8e71a01559d4.png)
Align after fullscreen;
![image](https://user-images.githubusercontent.com/25010528/102015476-8908a080-3d64-11eb-8ed1-1e2fcc94209e.png)

Settings:
![image](https://user-images.githubusercontent.com/25010528/102015526-e3a1fc80-3d64-11eb-9f37-f1a86392bf92.png)

**Browser and OS**
* Browser/browser version: **Chrome 87.0.4280.88**
* Operating system: **Win 7**
* Ultrawidify version: **4.4.10.1**

**Comment by tamius-han** [comment] 2020-12-13 23:22
Hi,

make sure you haven't set default alignment on youtube to something other than default. I'm having a bit of a trouble reproducing this issue either in Chrome or Firefox.

![Screenshot_20201214_001920](https://user-images.githubusercontent.com/12505802/102027048-04d50e00-3da2-11eb-8177-8406d4e8bb30.png)

If your settings are correct across all levels, mind sharing your full extension settings? You can export everything in extension options. If export button doesn't work, you can also copy the entire contents of `Super Advanced Settings` on the extension options page.

**Comment by BlackYuzia** [comment] 2020-12-14 09:56
@tamius-han https://pastebin.com/DpKVYWiq

**Comment by tamius-han** [comment] 2020-12-21 22:53
Hey,

sorry I lost the file with your settings and the link expired. Can you please share it again? 

(Side note: you _can_ drag .json files into github comments)

**Comment by BlackYuzia** [comment] 2020-12-22 09:13
@tamius-han https://pastebin.com/Qg9GueuA

**Comment by tamius-han** [comment] 2020-12-23 01:16
Ok, thanks.

I still cannot reproduce the issue, though — it doesn't happen for me. 

Can you please share your installed extensions?

**Comment by tamius-han** [comment] 2020-12-28 22:07
@BlackYuzia the newest version is on google for about 3 days now, so the extension probably updated to the latest version (4.5.1.1). Do you still experience the issue?

**Comment by BlackYuzia** [comment] 2020-12-29 12:06
Current version: 
![image](https://user-images.githubusercontent.com/25010528/103282603-f95b2700-49de-11eb-9742-dc80318f64f4.png)
The same bug:
![image](https://user-images.githubusercontent.com/25010528/103282617-0546e900-49df-11eb-8091-2025ce5bea45.png)

**Comment by tamius-han** [comment] 2020-12-29 13:12
...

Okay, can I please get the list of your other installed extensions?

**Comment by BlackYuzia** [comment] 2020-12-29 14:09
Current list:

![image](https://user-images.githubusercontent.com/25010528/103289608-472c5b00-49f0-11eb-8019-bf93efd484f8.png)

**Comment by tamius-han** [comment] 2020-12-29 17:11
Thanks & No, disabled extensions shouldn't matter. Just the enabled ones.

**Comment by tamius-han** [comment] 2020-12-29 18:04
And things still work for me.

* Do you have any tampermonkey scripts for youtube?

Furthermore, even with the extensions installed I haven't been able to reproduce the problem. If you can spare the time, I'd ask for a few favours.

1. I've made a special testing build of this addon. Please download and unzip to some folder: [ultrawidify-testing.zip](https://github.com/tamius-han/ultrawidify/files/5751644/ultrawidify-testing.zip)
2. Open [chrome://extensions/](chrome://extensions/) (the extension page in Chrome).
3. Disable ultrawidify
4. Toggle the 'developer mode' switch (upper right corner of the browser)
5. Click 'load unpacked' and select the folder where you've unzipped the extension
6. Open a youtube video, preferably the one where problem happens (or reload the page, if you've already on youtube)

The 'special' testing version of the addon will open a (unclosable) popup, like so:

![slika](https://user-images.githubusercontent.com/12505802/103303675-dcd2e500-4a06-11eb-80dd-56163327c842.png)

Please provide screenshot of this popup.

In addition to that, open the devtools (F12, but given 'Vue.js devtools' extension you know that), go to the HTML view and find the `<video>` element on the page. Select the video and screenshot the styles (start at the top, you can end once you reach "Inherited from `ytd-page-man...`" section. So basically, I need about this much:

![slika](https://user-images.githubusercontent.com/12505802/103304324-a39b7480-4a08-11eb-91fa-aa4633028873.png)


Thanks in advance.

**Comment by BlackYuzia** [comment] 2020-12-29 18:19
Note: 
![image](https://user-images.githubusercontent.com/25010528/103304967-a69b6280-4a12-11eb-82b0-91ceaf4a2e8f.png)
You forgot a latest symbol of version. I lost 1 min to understand why I get error :eyes: 


Second note:
I do not know what you do, but -
 - I didn't get ultra wide screen (by press R to reload)
 - I didn't get bug with align now

![image](https://user-images.githubusercontent.com/25010528/103305130-072a9f80-4a13-11eb-98ef-f25e941d28cd.png)

Do you anyway required data from console of developer?

**Comment by BlackYuzia** [comment] 2020-12-29 18:24
Anyway, I gave you they.

![image](https://user-images.githubusercontent.com/25010528/103305463-e1ea6100-4a13-11eb-96a9-377b8146f4fe.png)
![image](https://user-images.githubusercontent.com/25010528/103305466-e3b42480-4a13-11eb-9094-b80b1f0fc63b.png)
![image](https://user-images.githubusercontent.com/25010528/103305469-e4e55180-4a13-11eb-8b6e-16947d78c6f3.png)

**Comment by BlackYuzia** [comment] 2020-12-29 18:27
I actualy have a few errors in console
![image](https://user-images.githubusercontent.com/25010528/103305607-38579f80-4a14-11eb-9119-fb36a4794ccd.png)

**Comment by tamius-han** [comment] 2020-12-29 18:59
This is funny, I'm getting no such errors in the console.

Also I think I managed to reproduce the issue, finally.

* Happens on autoplay (or clicking a video in the sidebar) if autodetection doesn't detect any blackbars (and even then not always). Which explains a few thing why this didn't get reproduced.

**Comment by BlackYuzia** [comment] 2020-12-30 05:22
> or clicking a video in the sidebar

yep, I click video on sidebar. If this video would be opened first time I get this bug. If second time open or more this bug didn't show.

**Comment by ShootingStar91** [comment] 2021-01-07 02:01
I clicked "left" align once to fix an issue on one website. However, after that all websites are by default left, and I have to separately click "center" align on each website. Should I report this as a separate issue?

I only have uBlock Origin and ultrawidify installed.

**Comment by BlackYuzia** [comment] 2021-01-07 02:02
hmm. I press on "left align" too 🤔

**Comment by ShootingStar91** [comment] 2021-01-07 06:03
Reinstalling the addon made center-align the default again, however now I cannot press left-align again to fix the issue on one website because it will become the default again... I can live with that but this is obviously a bug.

Possibly there is a bug in the code of the left-align button or in the method that checks what is the current setting. I'd take a look myself but I don't know much js so I couldnt find the right files.

**Comment by tamius-han** [comment] 2021-01-10 17:11
> Should I report this as a separate issue?

Yes, this is a different issue, so it deserves its own task. However, i've given it a quick glance and I cannot reproduce the problem (I am testing on youtube for the time being).  Doesn't happen when I switch videos, doesn't happen when I reopen the browser, doesn't happen when I switch between different alignment options.

To start things with — can you please do as I ask in [this comment](https://github.com/tamius-han/ultrawidify/issues/125#issuecomment-752186546)?

Use [this link](https://github.com/tamius-han/ultrawidify/files/5792978/ultrawidify-testing.zip) to download the testing version instead of the one in that comment. 

———

> Note:
> ![image](https://user-images.githubusercontent.com/25010528/103304967-a69b6280-4a12-11eb-82b0-91ceaf4a2e8f.png)
> You forgot a latest symbol of version. I lost 1 min to understand why I get error eyes

Oh, figured out what the issue for that was. Didn't check it immediately because I thought it's a fluke, but I also can't tell people "ye use this" when you pointed out that the zip didn't work. I suppose I'm posting this so you can have a bit of a laugh on my expense or something.

The test build version format is `YYMM.DD.[Jenkins build number]`. Which is fine if I got the build off my CI machine ... except that in order to save myself some time, I built the testing version _locally_, without Jenkins.

Let's just say that there's no Jenkins build number without Jenkins.

**Comment by tamius-han** [comment] 2021-01-10 17:17
Whew, that's the _second_ time I did an oopsie whoopsie with uploading the incorrect version. This link has been retroactively edited into all other comments as well — posting in a new comment for visibility (because people who only reads emails won't get the correct link)

[uw-testing.zip](https://github.com/tamius-han/ultrawidify/files/5792986/uw-testing.zip)

**Comment by BlackYuzia** [comment] 2021-01-10 18:53
@tamius-han so, you fix my current bug?

**Comment by tamius-han** [comment] 2021-01-10 19:44
Yes, it should be fixed. It should be fixed for about 10-12 days now, not sure when the 4.5.1.2 got through the CWS review (because apparently the new minor version — featuring some disney plus CSS and removal of the popup for edge users — that I uploaded about an hour ago just cleared the Chrome Web Store review in a record-shattering time).

**Comment by tamius-han** [comment] 2021-01-10 19:48
... oh god did I speak too soon. I just managed to catch this same bug in another different way.

**Comment by ShootingStar91** [comment] 2021-01-11 07:39
> > Should I report this as a separate issue?
> 
> Yes, this is a different issue, so it deserves its own task. However, ...

I cannot reproduce it now myself either anymore. I wonder if it was fixed when I reinstalled the addon some days ago. Maybe that updated it or something. Now the align didn't get stuck, I have no idea why.

**Comment by tamius-han** [comment] 2021-01-13 00:14
I think I've finally got this issue fixed. The fix will be releases by the end of the week + however long it takes for CWS to process the extension submission.

**Closed** 2021-02-03 15:44 UTC
Labels: Chrome, Firefox, Waiting for release, bug
