### ISSUE TITLE
"Video Settings" Menu page/tab does not detect any clicks on the buttons 

### ISSUE THREAD

**Issue by githubbc1** [tamius-han/ultrawidify#93] opened 2020-02-08 20:07 UTC
Hi Team,
     This addon is promising, unfortunately for me, it suffers from UI issues.
On windows 10 os, When "Video Settings" menu Tab of this addon is clicked, in the Video Settings options view of this addon, NO  buttons worked!
Buttons under 'Cropping mode:'  (example: Fit Height), 'Stretching mode:' (example button: Hybrid) , and under 'Video Alignment' (example: Center)  did NOT work.

Could you kindly solve this, May be you could put check Radio buttons instead of regular clickable button areas if that makes the code to easily get the user input?

Thanks in advance and looking forward to fix for this good addon.

**Comment by Insan1ty0ne** [comment] 2020-02-08 21:03
I am experiencing this issue as well. The extension is currently not working AT ALL for me.

Windows 10 Edition: Education
Windows 10 Version: 1909
Windows 10 OS Build: 18363.628
Google Chrome Version 81.0.4044.9 (Official Build) dev (64-bit)
Extension Version: 4.4.4

If you need any other information just let me know.

**Comment by tamius-han** [comment] 2020-02-08 23:19
Reproduced on some setups.

In the mean time, keyboard shortcuts should still work.

**Comment by tamius-han** [comment] 2020-02-09 02:37
Whoopsie daisy.

I knew my extension requires additional review on Chrome Web Store. I didn't know that changing extension description (without actually providing updated version of extension)  also triggers said review process, which can take days. 

I think the fix is more or less ready, though. It wasn't tested very thoroughly yet, but it looks like the popup is working now.

# What can you do (in the mean time)

Aside from using Firefox or keyboard shortcuts, you could run a [testing build](https://stuff.lionsarch.tamius.net/ultrawidify/testing/). Version **2002.09.87** should contain the fixes. Note that you will need to enable developer mode and load unpacked (temporary) extension to do that.

On the positive side, though, Google Chrome will not remove temporary/unpacked extensions between browser restarts, so this is semi-viable workaround if you want to use the extension popup until I go through both extension reviews (based on previous experience, this could take about a week). 

If you do going this route, please provide some feedback re: whether everything works as it should (after all, this is a 2 AM fix).

# What went wrong (technical stuff)

> May be you could put check Radio buttons instead of regular clickable button areas if that makes the code to easily get the user input?

Certainly not this. It's never this.

For people not familiar with how browser extensions work (and I'll over-simplify things) — there's roughly three sorts of scripts extension has:

* content scripts
* the extension popup (this one is self explanatory)
* background script

Content scripts run on every webpage and boss the page around. You know how extension makes the video fit the screen when you press the relevant button? Content script does that. There is a few things that you can't do with content scripts: I don't think a popup can communicate directly with the content scripts (and vice versa). You can't detect when user switches tabs. You can't inject CSS from content script.

That's where the background script comes in. It does everything a content script can't or doesn't have permission to do. The thing relevant to this bug: you need background script to pass messages between popup and content scripts. There's two ways of passing those messages. Content scripts pass messages using only one of these two ways, popups use both (or only the other, I'm not actually sure).

Background script listens for these messages, and it has to listen for both methods. Background script also sometimes needs to do certain things, based on what the message is. As such, there was a lot of code repetition, and writing same code in two places is bad. The messaging code was also turning into mom spaghetti as well, so I decided to do a little cleanup. 

So there's this two functions:

```js
async processReceivedMessage(message, port){
    if (message.forwardToContentScript) {
      this.sendToFrame(message, message.targetTab, message.targetFrame);
      return;
    }
    if (message.cmd == "something" ) {
      // do something
    } else if (message.cmd == "something else") {
      // do something else
    } ...
    // shit ton more code after this
}

processReceivedMessage_nonpersistent(message, sender, sendResponse){
    if (message.forwardToContentScript) {
      this.sendToFrame(message, message.targetFrame);
      return;
    }

    if (message.cmd == "something" ) {
      // do something
    } else if (message.cmd == "something else") {
      // do something else
    } ...
    // shit ton more code after this
```
And really, imagine the list of if/else-if/else statements goes on forever. So I decided  to roll these two into a single function:

```js
processMessageForReals(message, portOrSender) {
    if (message.forwardToContentScript) {
      this.sendToFrame(message, message.targetTab, message.targetFrame);
      return;
    }
    if (message.cmd == "something" ) {
      // do something
    } else if (message.cmd == "something else") {
      // do something else
    } ...
    // shit ton more code after this
}

async processReceivedMessage(message, port){
    this.processMessageForReals(message, port);
}

processReceivedMessage_nonpersistent(message, sender, sendResponse){
    this.processMessageForReals(message, port);
}

```

There's one problem, though. The second method had only two arguments in `this.sendToFrame()` call, but now it wants three. Back in the day, first one was message. Second was target frame.

`sendToFrame()` requires 'frame' as a third one.

Except it doesn't, really. Back when the function was made, an assumption was made that tab will be either a number (in which case it'll be treated as a tab) or not a number, in which case it's gonna be treated differently:

async sendToFrame(message, tab, frame) {
  if (isNaN(tab)) {
    if (frame === '__playing') {
      message['playing'] = true;
      this.sendToAll(message);
      return;
    } else if (frame === '__all') {
      this.sendToAll(message);
      return;
    }
    [tab, frame] = tab.split('-') // <---- pay attention here
  }
  // do the rest of the magic
}

Obviously, that assumption is broken. After the functions were merged, `frame` is always the _last_ argument. This means that `tab` can be undefined.

If 'tab' is undefined, we don't get the information we need.

If we don't get the information we need, nothing is going to happen.

And of course this issue only effected some very specific options (read: not the ones I was working on).

**Moral of the story:** variable naming is important. Also don't be a dumbass when naming variables because the future you is gonna hate you for it one year down the line.

Also I think I just lost my right to make fun of Microsoft breaking Windows search to the point it didn't work at all (as opposed to 'worked like shit', which was MO since Win10 release).

**Closed** 2020-02-09 02:39 UTC
Labels: Chrome, Firefox, bug

**Comment by Insan1ty0ne** [comment] 2020-02-09 03:02
Unfortunately: https://stuff.lionsarch.tamius.net/ultrawidify/testing/2002.09.87/Ultrawidify-nightly-2002.09.87-chrome.zip reports "404 Not Found". Perhaps the build just hasn't had time to finish building / uploading yet?

**Comment by tamius-han** [comment] 2020-02-09 15:05
I've went ahead and triggered another build — [try this link](https://stuff.lionsarch.tamius.net/ultrawidify/testing/2002.09.88/Ultrawidify-testing-2002.09.88-chrome.zip).

**Comment by githubbc1** [comment] 2020-02-10 21:46
> I've went ahead and triggered another build — [try this link](https://stuff.lionsarch.tamius.net/ultrawidify/testing/2002.09.88/Ultrawidify-testing-2002.09.88-chrome.zip).

Thanks for responding with test buil.
The "Extension Settings" tab is able to detect clicked button and highlight it.

However the "Video Settings"  tab did not reflect the clicked buttons, clicked buttons didnt stay highlighted.

Thank you in advance

**Comment by tamius-han** [comment] 2020-02-10 21:53
> However the "Video Settings" tab did not reflect the clicked buttons, clicked buttons didn't stay highlighted.

This is by design, because some behaviour things weren't resolved yet for edge cases (and few other reasons).

**Comment by githubbc1** [comment] 2020-02-10 22:12
> > However the "Video Settings" tab did not reflect the clicked buttons, clicked buttons didn't stay highlighted.
> 
> This is by design, because some behaviour things weren't resolved yet for edge cases (and few other reasons).

Hi Team,
      In that case, do the buttons in "Video Settings" tab receive input and then store the user choice (among buttons) made even though visually the button doesnot remain highlighted?
The "Extension Settings" and "Site settings" tabs are able to display buttons as highlighted though.

(my usecase is to just zoom video to height after removing black bars at top and bottom of video, if there are top and bottom bars in the video, towards that goal, i am trying to use Ultrawidify to achieve my usecase to good extent)

Thanks in advance

Thanks in advance

**Comment by tamius-han** [comment] 2020-02-10 23:10
> do the buttons in "Video Settings" tab receive input and then store the user choice

If we're pedantic — they don't store user choice. They just shout "hey someone wants to fit video to [whatever]" at the background script (which passes the note to the video), and then promptly forget about the interaction because technical reasons.

But yes, pressing buttons in video settings is kinda like pressing the button on the keyboard. Keys don't remain stuck when you press them, either, but the extension still gets the signal.

> The "Extension Settings" and "Site settings" tabs are able to display buttons as highlighted though.

Because those two work in significantly different ways. The settings on those tabs are (semi)permanent. Settings in video tab get reverted every time you reload the page.

**Comment by githubbc1** [comment] 2020-02-11 00:06
Hi Team,
     Tested the "Video Settings" tab on the latest build, Youtube videos didnt stretch as per chosen setting,

Maybe it was for my pc and hope it worked for others.

Than you for your time
