### ISSUE TITLE
Ultrawidify breaks Danish NemLogin

### ISSUE THREAD

**Issue by VirtualSatai** [tamius-han/ultrawidify#96] opened 2020-02-24 08:21 UTC
**Describe the bug**
When I have Ultrawidify enabled, I'm unable to use the danish central government login system, I get a JSON parsing error

**To Reproduce**
Go to: https://nemlog-in.dk/login.aspx/noeglefil
Follow their install instructions
Enable Ultrawidify
Go to https://nemlog-in.dk/login.aspx/noeglefil -> "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"

**Expected behavior**
No Javascript errors

**Screenshots**
I recorded a small video: https://streamable.com/pipgq
![image](https://user-images.githubusercontent.com/1919650/75137068-e56fd600-56e6-11ea-990f-0e366c3f79c6.png)

**Browser and OS**
 * Browser/browser version: Firefox 73.0.1
 * Operating system: Windows 10 1803
 * Ultrawidify version: 4.4.4.2

**Comment by tamius-han** [comment] 2020-03-01 19:51
Sorry for a late response.

Apparently I need a Danish ID or driver's license to get the login stuff, so I don't think I'll be able to handle this one.

Can you please do the following:

1. When on the page, click the popup, go to 'site settings' and click 'disable':

![image](https://user-images.githubusercontent.com/12505802/75632514-0069ab00-5bfd-11ea-9b09-c8be20e76459.png)

Does that fix the issue? (I'm asking because there's a chance it doesn't, due to technical reasons). 

---

I have also tried to do something that would fix the issue in a bit more proper way. Regardless of whether that fixes the issue, I would appreciate if you tested a testing version and see if it fixes the problem:

* Download the version [2003.01.100 from here](https://stuff.lionsarch.tamius.net/ultrawidify/testing/) 
* Extract the zip file somewhere and load it as unpacked extension (instructions [here](https://github.com/tamius-han/ultrawidify/wiki/Nightly-and-testing-versions#installing-nightly-or-testing-version)). Make sure that store version of Ultrawidify is disabled when giving testing version a spin.

Thanks in advance.

**Comment by VirtualSatai** [comment] 2020-03-01 22:27
Hi, 

Using 4.4.4.2, I still get the error even if the extension is "disabled" using the global setting: 
![image](https://user-images.githubusercontent.com/1919650/75635047-3f0a6000-5c13-11ea-91c2-b04cc9125cbd.png)

2002.01.100 still produces the same error for me.

Regarding reproduceability, try going to this site:
https://mit.virk.dk/login
Then press "Log ind"
![image](https://user-images.githubusercontent.com/1919650/75635123-da9bd080-5c13-11ea-8fff-adfc770b6f99.png)
Then press "Log on with code file"
![image](https://user-images.githubusercontent.com/1919650/75635127-e6879280-5c13-11ea-9fdb-6338a22b24dd.png)

There should be no requirements to get there to reproduce the issue. 
If the problem is resolved (or addon disabled) you'll see the following:
![image](https://user-images.githubusercontent.com/1919650/75635187-4847fc80-5c14-11ea-9a66-a5620fa91c84.png)

**Comment by tamius-han** [comment] 2020-03-02 21:51
I can reproduce it now, thanks.

**Comment by tamius-han** [comment] 2020-03-08 19:58
Good news, this seems to be fixed on my end (you can try the latest testing version). 

Update will be released some time this/next week.

**Comment by tamius-han** [comment] 2020-03-09 22:00
:tada: Version with the fix is up on the AMO

**Closed by tamius-han** 2020-03-09 22:00 UTC
Labels: Waiting for release, bug
