### ISSUE TITLE
autodetection not working on watch.tatasky.com

### ISSUE THREAD

**Issue by dineshdutta101** [tamius-han/ultrawidify#94] opened 2020-02-13 05:42 UTC
**Describe the bug**
From past 3days auto video stretch not working on watch.tatasky.com while playing any channel. earlier it used to automatically stretch the video. but since few days i have to everytime manually press s or e to stretch the video everytime i play a new live channel

**To Reproduce**
please enable auto video stretch for watch.tatasky.com

**Screenshots**
![tatasky](https://user-images.githubusercontent.com/34351416/74404841-9f4a8500-4e51-11ea-94b7-073c45eda3a0.jpg)

**Browser and OS**
 * Browser/browser version:Chrome
 * Operating system:Windows 10
 * Ultrawidify version:Latest

**Additional info**
Any other things you want to say.

**Comment by tamius-han** [comment] 2020-03-01 19:58
Does tatasky have any channels that do not require login?

Otherwise I can't reproduce this, as other sites don't appear to have this problem.

**Comment by tamius-han** [comment] 2020-03-09 22:02
Possibly related to #91 

Closing cos #91 was resolved.

**Closed by tamius-han** 2020-03-09 22:02 UTC
Labels: No info provided, help wanted, needs-info
