### ISSUE TITLE
[panopto] Videos are clipped when horizontally longer than the display

### ISSUE THREAD

**Issue by saschanaz** [tamius-han/ultrawidify#118] opened 2020-10-30 12:57 UTC
**Describe the bug**

Panopto incorrectly shows 16:9 video way too big on 3:2 display.

(I'm definitely using a 21:9 monitor connected to my Surface Pro but the laptop display is still 3:2.)

**To Reproduce**

1. Access https://mozilla.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ae2caf59-9253-4ee3-b4cb-ac410123959d
2. Make the video fullscreen

**Expected behavior**
What do you think should happen instead?

![image](https://user-images.githubusercontent.com/3396686/97707313-69206480-1ab7-11eb-8f52-a317f7115e89.png)

**Screenshots**

<img alt="Screenshot" src="https://webcompat.com/uploads/2020/10/6f163c19-04ef-4a76-960f-264e776c4241.jpeg">

**Browser and OS**
 * Browser/browser version: Firefox 82/84
 * Operating system: Windows 10
 * Ultrawidify version: 4.4.10

**Additional info**

The same doesn't happen on YouTube.

**Comment by tamius-han** [comment] 2020-11-05 19:48
Think I'm gonna (eventually) close this with 'wontfix,' blacklist the site by default and call it a day because:

* I really don't like the way things are coded
* It's not like anyone uses this site
* And for the handful of users that do, unnecessary black bars prolly don't happen a lot given they seem to mostly host talks and stuff.

Notes to self:

* Likely broken by `width: initial !important` bit of CSS that is always enforced (which needs to be there because twitch and IIRC Hulu.
* Caused by the fact we don't do `height: initial !important`, because that breaks a few other sites (having both width and height on `initial: important` may result in videos the size of a postage stamp).
* Or maybe we could decide which of the two (width, height) we set to `initial !important` based on player aspect ratio. Prelimiary toying with inspector shows promising results

**Comment by saschanaz** [comment] 2020-11-05 19:56
Yeah, I just switched to enable it only for allowlisted sites so that it won't affect random sites. It's not that every service has broken videos anyway.

**Comment by tamius-han** [comment] 2020-12-23 01:13
Turns out this was not just an issue on this site — it was also happening on Netflix and ... on a lot of sites, actually.

Figured why. Things work now, unless you try to do 'fit height' ... in which case, they don't always work quite (at least as far as Netflix is concerned).

**Closed by tamius-han** 2020-12-23 01:13 UTC
Labels: Chrome, Firefox, bug
