### ISSUE TITLE
On Prime Video, when I set to "Fit Width" or "21:9", it works until I go full screen

### ISSUE THREAD

**Issue by meechgalhuquot** [tamius-han/ultrawidify#132] opened 2021-01-30 10:20 UTC
When I attempt to go fullscreen, all of a sudden it stays fit to the width of the screen but squashes the vertical portion of the screen. Doesn't matter if its F11 fullscreen or pushing the fullscreen button in the player. Last time I attempted to use it ~2 weeks ago, the extension worked fine, it just isn't anymore

**Comment by tamius-han** [comment] 2021-01-30 11:51
This is a Chrome/Edge issue on Windows, and should also happen on youtube (and just about every time).

As of yesterday evening, I am also able to reproduce this issue, and I've already got a sorta-workaround in the works. It's gonna go out today, but it could take a few days before the new version of the extension is approved on CWS and Edge stores, though.

In the mean time you can:

* disable hardware acceleration
* don't use a nVidia GPU, because to date every single person reporting this issue has been using nVidia
* zoom for 18:9
* live with the pillarbox
* open browser console while in fullscreen (F12) and resize it to the smallest possible space (the console must be attached to the side or to the bottom of the page, it doesn't work if it's in a separate window)

Please reporting this issue to Chrome (and/or Edge) developers. Press `Alt + Shift + I` (or go to chrome/edge menu -> help -> report a problem) and enter the following into the 'please provide accurate description' box:

```
CSS transform: scale property doesn't work for certain factors while video is being played in full screen mode.

Specifically, the issue seems to appear when the following conditions are met:

* Hardware acceleration is turned on.
* You are using an ultrawide (21:9) monitor or wider
* the video is being played in fullscreen
* after transform: scale(x,y) is applied, the video is both roughly taller and roughly wider than the display (in practice, the bug appears slightly before reaching this point)

Under these conditions, the video will be stretched to fill the monitor (in a `object-fit: fill` kind of way. This means that if the video is scaled using `transform: scale(x)` or `transform: scale(x,x)`, the scaling will behave as if the video was scaled using `transform: scale(x, 1)` — which is incorrect behaviour.

Bug demonstration:
* https://youtu.be/zWA4e_mTTeY

This issue can be reproduced on all platforms that I've tried so far:
* https://www.youtube.com/watch?v=jPEYpryMp2s
* https://vimeo.com/channels/staffpicks/169599296
* https://streamable.com/vrb4w
* https://www.twitch.tv/videos/330639009?t=1h50m0s
* https://old.reddit.com/r/Guildwars2/comments/cxtf9r/the_rytlock_and_bangar_teaser/
```

**Comment by meechgalhuquot** [comment] 2021-01-30 13:22
You are correct that this is on an Nvidia card. I already have had hardware acceleration disabled due to separate issues. Interestingly I managed to get it to work in the new Edge with no issues, without making any changes

**Comment by meechgalhuquot** [comment] 2021-02-03 13:32
I am running the most recent version and now I get no change to the video feed at all in Edge, Chrome, or Firefox. See video in link

[Dropbox](https://www.dropbox.com/s/j7x73nfq8a4jjmm/Ultrawidify-no-effect.mp4?dl=0)

**Comment by meechgalhuquot** [comment] 2021-02-03 13:38
I just downloaded the most recent nightly and loaded it into chrome and it appears to be working

**Comment by tamius-han** [comment] 2021-02-03 15:59
Well at least the video doesn't get squished anymore.

Pseudo-witty remarks aside: That's funny, because the latest nightly build should be exactly the same as stuff you get from the CWS. If you remove and then install Ultrawidify on Chrome Web Store, is the issue resolved?

If that doesn't fix the issue, could you please do the following:

1. Install [Save Page WE](https://chrome.google.com/webstore/detail/save-page-we/dhhpefjklgkmgeafimnjhojgjamoafof) extension.
2. Open Prime and pick any video
3. Start playing said video and let it play for about 30 seconds or so
4. Right click on the floppy icon -> save selected tabs -> standard items:
![image](https://user-images.githubusercontent.com/12505802/106772585-744bd900-6640-11eb-9936-35629c185326.png)
5. (optional) Open the resulting .html file with notepad and do a quick search for any personally identifying info (e.g. email). Feel free to remove those.
6. Zip the HTML file and attach it to your post.

**Comment by iamtau** [comment] 2021-04-08 16:35
Hi, is this issue supposed to be fixed now? Just wanted to know because I'm experiencing it now, on Edge.
I don't have an NVidia GPU, so not sure what the issue is. I tried re-installing it from the Chrome Store but it didn't help.
Any help is appreciated, your extension has been a godsend so far!

**Comment by tamius-han** [comment] 2021-04-08 17:19
Amazon prime seems to be a bit of a mess. Some people say it works for them, some people say it doesn't, and some people say it only works sometimes. And I don't have access to prime at this time, and nobody has provided me with a copy of the page saved with Save Page WE addon (as per my last comment).




Actually wait, I misremembered. In my emails, someone _did_ actually provide me with a capture of prime video, but it appears that Amazon Prime does some stuff that made the capture not very useful for the purpose of debugging. This is a dead end.

You can also try to play with the **Player detection settings**  under _Advanced Settings' tab of the popup:

![image](https://user-images.githubusercontent.com/12505802/114068743-82b3ac80-989e-11eb-9a40-1debffbd9c11.png)

Untick the 'detect automatically', tick the "specify player node parent index" checkbox, and try changing the value. Start with one, save the settings, refresh the page. Check if extension works. If it doesn't, increase the number by 1 and try again.

Do that until you get to 10-12. If extension doesn't start working by then, then the problem would probably require some additional CSS to fix.

**Comment by iamtau** [comment] 2021-04-08 18:00
Oh, I'm sorry I didn't mention it, but this isn't on Amazon Prime. I'm actually seeing this on YouTube and another website. I tried tweaking the Player Detection settings but to no avail...

**Comment by tamius-han** [comment] 2021-04-08 20:27
Ok, I've got a quick favour to ask. 

1. Go to youtube.
2. Pick any video, go to fullscreen, press 'fit to width' or 'crop to 21:9'.
3. If the issue appears as you say it does, press F12. Select the 'console' tab in the window that appears.

You should see something like this (though the window could be white instead of dark):
![slika](https://user-images.githubusercontent.com/12505802/114091719-4b062e00-98b9-11eb-82ba-e5ffa8b34df3.png)

Take screenshot of all the messages. Head to the thread #144 and post the screenshots there. Please post screenshots in that thread and not here, so my bug reports remain somewhat organized.

Thanks for taking your time.

**Comment by carrollj** [comment] 2021-04-18 20:50
I was having issues with Amazon Prime, but setting "Player is n-th parent of video" to `3` fixed the issue for me.

**Comment by zHalfinity** [comment] 2023-04-23 20:23
I had the same issue on Brave on Windows with GTX980 and I fixed it with setting use-angle flag to OpenGL
```
Choose ANGLE graphics backend
Choose the graphics backend for ANGLE. D3D11 is used on most Windows computers by default. Using the OpenGL driver as the graphics backend may result in higher performance in some graphics-heavy applications, particularly on NVIDIA GPUs. It can increase battery and memory usage of video playback. – Windows

[#use-angle](chrome://flags/#use-angle)
```

**Closed** 2024-06-12 01:02 UTC
